theme: jekyll-theme-minimal
title: Jiayu Zhang's Pages
description: Bookmark this to keep an eye on my project updates!
url: "https://kuiningzzzz.github.io"
baseurl: ""

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag